# Generated by Django 2.2 on 2020-07-27 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog_park_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='breed',
            field=models.CharField(blank=True, default='not provided', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dog',
            name='gender',
            field=models.CharField(blank=True, default='not provided', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='dog',
            name='name',
            field=models.CharField(blank=True, default='not provided', max_length=100, null=True),
        ),
    ]
