# Generated by Django 2.2 on 2020-07-28 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog_park_app', '0002_auto_20200726_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
