# Generated by Django 2.2 on 2020-07-29 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dog_park_app', '0003_dog_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playdate',
            name='address',
        ),
    ]
