# Generated by Django 2.2 on 2020-07-29 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog_park_app', '0004_remove_playdate_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='playdate',
            name='address',
            field=models.CharField(default='See address in Google Map', max_length=255),
            preserve_default=False,
        ),
    ]
