# Generated by Django 2.2 on 2020-07-29 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dog_park_app', '0005_playdate_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playdate',
            old_name='address',
            new_name='park_address',
        ),
    ]
