# Generated by Django 2.2 on 2020-07-31 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog_park_app', '0010_auto_20200730_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='image',
            field=models.ImageField(blank=True, default='placeholder.png', null=True, upload_to='images/'),
        ),
    ]
